...
struct task_struct {
	...
	struct thread_info		thread_info;
	volatile long			state;
	...
	void				*stack;
	...
	int				on_cpu, on_rq;
	...
	int				prio;
	int				static_prio;
	int				normal_prio;
	unsigned int			rt_priority;
	const struct sched_class	*sched_class;
	struct sched_entity		se;
	...
	unsigned int			policy;
	int				nr_cpus_allowed;
	...
	pid_t				pid;
	pid_t				tgid;
	...
	struct task_struct __rcu	*real_parent;
	...
	struct list_head		children;
	struct list_head		sibling;
	...
	struct pid			*thread_pid;
	...	
};
...


